service: my-bills

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
