service: my-bills

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
